# Site
title: Aeleftheriadis
description: Web Developer's Blog
url: https://aeleftheriadis.github.io
#url: http://localhost:4000
logo: aeleftheriadis.png                                       # Site logo
locale: en_US

# Left Block Images
background:
  homepage: images/home.png                           # this image will be shown on homepage's left block
  post-list: images/posts.jpg            # this image will be shown on post list page
  default-post: images/post.jpg   # this image will be shown when post's front matter doesn't specify any image

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
sass:
  sass_dir:         assets/_sass
  style:            compressed

# Google Analytics
google-analytics: UA-83650817-1

# Social Links
email:              athanasios.eleftheriadis@gmail.com
google.plus:        athanasios.eleftheriadis@gmail.com
twitter:            suomilk
facebook:           suomilk
github:             aeleftheriadis
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           athanasios-eleftheriadis
#xing:              username
instagram:          athanasioseleftheriadis
lastfm:             it0247
#tumblr:            username
pinterest:          suomilk
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:            UC4Mu_aLX4sh5CcycKGVzIZQ
soundcloud:         athanasios-eleftheriadis
#weibo:             username
#flickr:            username
codepen:            aeleftheriadis
rss:                feed
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
#behance:           username
bitbucket:          aeleftheriadis
meetup:             187466502

# Gems
gems:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

# Exclude list
include: [_pages]
exclude: [README.md, Gemfile, Gemfile.lock, _site, src, vendor, CNAME, LICENSE, Rakefile, .sass-cache, .DS_Store]
